# This file was generated by Actions Bot. DO NOT EDIT.
class HarborCli < Formula
  desc "Harbor CLI for interacting with Harbor registry"
  homepage "https://goharbor.io"
  version "0.0.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.18/harbor-cli_0.0.18_darwin_amd64.tar.gz"
      sha256 "44d9e38ce108199c3c09b98726dd04e8c2f89afae04219e9192d0bcb15903050" # darwin_amd64

      def install
        bin.install "harbor-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.18/harbor-cli_0.0.18_darwin_arm64.tar.gz"
      sha256 "75404b797ec94193a3043e3a40953e7322f9794c75f162e706c6689324cfd422" # darwin_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

 on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.18/harbor-cli_0.0.18_linux_amd64.tar.gz"
      sha256 "6e209079d33ed2c3a095b98d4f8b97d0469d755bb362e2c99920be5956642964" # linux_amd64

      def install
        bin.install "harbor-cli"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.18/harbor-cli_0.0.18_linux_arm64.tar.gz"
      sha256 "f37f4e9b9be81a74496800d413d1d1c39f4a9821bbd3f0f0f67591a22d918a4a" # linux_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

  test do
    system "#{bin}/harbor-cli", "version"   # Formula test (after install)
  end
end
