# This file was generated by Actions Bot. DO NOT EDIT.
class HarborCli < Formula
  desc "Harbor CLI for interacting with Harbor registry"
  homepage "https://goharbor.io"
  version "0.0.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.24/harbor-cli_0.0.24_darwin_amd64.tar.gz"
      sha256 "e9c0f6b31d007100473bb8d8abd37bd44ca068615c985abf9b197c25ee7f10b8" # darwin_amd64

      def install
        bin.install "harbor-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.24/harbor-cli_0.0.24_darwin_arm64.tar.gz"
      sha256 "de18c1da6dbc34917c42dfc575b6ee361b358059421b8eac773bcec96ffa3439" # darwin_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

 on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.24/harbor-cli_0.0.24_linux_amd64.tar.gz"
      sha256 "e777518c50f7d7c3f08ca6e5515185b82aaa3f83d2b00f800b9495da4def3113" # linux_amd64

      def install
        bin.install "harbor-cli"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.24/harbor-cli_0.0.24_linux_arm64.tar.gz"
      sha256 "802be0aec20c0e9f18b4db0dacee5e658490164cd08e178f3dc8d952f2db4ea2" # linux_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

  test do
    system "#{bin}/harbor-cli", "version"   # Formula test (after install)
  end
end
