# This file was generated by Actions Bot. DO NOT EDIT.
class HarborCli < Formula
  desc "Harbor CLI for interacting with Harbor registry"
  homepage "https://goharbor.io"
  version "0.0.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.26/harbor-cli_0.0.26_darwin_amd64.tar.gz"
      sha256 "de14dad1b85d59c6621f87ffbd5c919b150b57fe28363411fd19011c8892ef8d" # darwin_amd64

      def install
        bin.install "harbor-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.26/harbor-cli_0.0.26_darwin_arm64.tar.gz"
      sha256 "1cddaf4260358f9fef64d6e6624928922716e711ff25158745bd1eba32cc3b11" # darwin_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

 on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.26/harbor-cli_0.0.26_linux_amd64.tar.gz"
      sha256 "d05717300dbea2096ce601cfa43ba1f1b38a6dfa35fb977755b1dffcd93914df" # linux_amd64

      def install
        bin.install "harbor-cli"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/goharbor/harbor-cli/releases/download/v0.0.26/harbor-cli_0.0.26_linux_arm64.tar.gz"
      sha256 "da48dcc6a7082a642e4c868c92e3658b9e9062a789a6341df8fb768ca59fd9c5" # linux_arm64

      def install
        bin.install "harbor-cli"
      end
    end
  end

  test do
    system "#{bin}/harbor-cli", "version"   # Formula test (after install)
  end
end
